# Generated by Django 5.0.6 on 2024-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
