# Generated by Django 5.0.6 on 2024-06-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('honeycomb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hive_conversations', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='nectar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nectar_conversations', to='honeycomb.nectar'),
        ),
    ]
