# Generated by Django 5.0.6 on 2024-06-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('communication', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.document'),
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.document'),
        ),
    ]
