# Generated by Django 5.0.6 on 2024-06-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_document_file_id'),
        ('honeycomb', '0007_historicalhive_vector_store_id_hive_vector_store_id'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='nectar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.nectar'),
        ),
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='common.document'),
        ),
        migrations.AddField(
            model_name='task',
            name='nectar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='honeycomb.nectar'),
            preserve_default=False,
        ),
    ]
