# Generated by Django 5.0.6 on 2024-06-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeycomb', '0007_historicalhive_vector_store_id_hive_vector_store_id'),
        ('task', '0002_historicaltask_nectar_task_documents_task_nectar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='honeycomb.contract'),
        ),
    ]
