# Generated by Django 5.0.6 on 2024-06-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('honeycomb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='bee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='contract_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='historicalbee',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbee',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='bee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhive',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhiverequest',
            name='bee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='historicalhiverequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='bee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnectar',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hive',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_hives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hive',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='hive_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='historicalnectar',
            name='nectar_hive',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='hive',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='historicalhiverequest',
            name='hive',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='hiverequest',
            name='bee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='hiverequest',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='hive_request_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='hiverequest',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='membership',
            name='bee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='membership',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='hive',
            name='hive_bees',
            field=models.ManyToManyField(through='honeycomb.Membership', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='nectar',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='nectar_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='nectar',
            name='nectar_hive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nectars', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='nectar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='honeycomb.nectar'),
        ),
        migrations.AddField(
            model_name='contract',
            name='nectar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='honeycomb.nectar'),
        ),
        migrations.AddField(
            model_name='report',
            name='bee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bee_reports', to='honeycomb.bee'),
        ),
        migrations.AddField(
            model_name='report',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='report_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='report',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hive_reports', to='honeycomb.hive'),
        ),
        migrations.AddField(
            model_name='report',
            name='nectar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nectar_reports', to='honeycomb.nectar'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('hive', 'bee')},
        ),
    ]
