# Generated by Django 5.0.6 on 2024-06-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeycomb', '0004_hive_tags_nectar_tags_alter_bee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bee', to=settings.AUTH_USER_MODEL),
        ),
    ]
