# Generated by Django 5.0.6 on 2024-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeycomb', '0005_alter_bee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
