# Generated by Django 5.0.6 on 2024-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeycomb', '0006_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhive',
            name='vector_store_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hive',
            name='vector_store_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
